// SPDX-License-Identifier: GPL-3.0-or-later
//
// CALC3 key ROM.
//
// The keyed decryption path picks one of 256 64-byte keys by a byte in the
// block header. Only 36 of those 256 exist -- MAME fills the rest with -1,
// its "no such key" marker -- so this stores the 36 and an index from key
// byte to slot. 2.3 KB rather than 16 KB, and about 2 M10K rather than 13,
// which matters on a branch where block memory is the binding constraint.
//
// A key byte with no key asserts `absent`. That is a REFUSAL, not a default:
// decrypting with somebody else's key would produce plausible-looking wrong
// bytes, and those bytes are 68000 instructions the game then executes. MAME
// calls fatalerror() at the same point. The sequencer must stop.
//
// Data generated by tools/gen_calc3_keys.py from MAME's kaneko_calc3.cpp,
// BSD-3-Clause (Luca Elia, David Haywood). It is not ROM-derived -- the CALC3's
// internal ROM has never been dumped and this is reverse-engineered constant
// data in MAME's source -- so there is nothing to load over MRA and hard rule 2
// does not apply. See that tool's header.

module kaneko_calc3_keys #(
    parameter KEYS_HEX = "rtl/mcu/calc3_keys.hex",
    parameter IDX_HEX  = "rtl/mcu/calc3_keyidx.hex",
    // SIXTY-FOUR SLOTS, though only 36 keys exist. The address is
    // slot * 64 + index, twelve bits; at 36 slots most of those addresses
    // are out of range, Quartus cannot prove the index is bounded, and it
    // builds the table from LOGIC rather than inferring a memory -- 378
    // ALMs and zero M10K, measured. Padding makes every address valid.
    parameter int unsigned NSLOTS = 64
) (
    input  wire       clk,
    input  wire [7:0] key_sel,     // the block header's key byte
    input  wire [5:0] key_idx,     // byte within the key, i & 0x3f
    output wire  [7:0] key_data,   // registered, one cycle after the inputs
    output logic       absent      // key_sel names no key; registered alongside
);

  localparam logic [5:0] NONE = 6'h3f;   // out of range for 36 slots

  // Two memories rather than one 16 KB array. The index is small enough to
  // land in logic; the keys want a block.
  (* ram_style = "block" *) logic [7:0] keys [0:NSLOTS*64-1];
  logic [5:0] kidx [0:255];

  initial begin
    $readmemh(KEYS_HEX, keys);
    $readmemh(IDX_HEX,  kidx);
  end

  wire [5:0] slot = kidx[key_sel];

  // The address is computed from the slot BEFORE the registered read, so the
  // absent case must be steered away from a real address rather than allowed
  // to index past the array.
  wire [11:0] addr = {slot[5:0], 6'd0} + {6'd0, key_idx};

  // THE READ IS UNCONDITIONAL, and the absent case is handled after it.
  //
  // Writing `key_data <= (slot == NONE) ? 8'h00 : keys[addr]` reads the memory
  // only on one branch, and a conditional read defeats inference outright --
  // already on record in this repository. Quartus built the whole table from
  // logic instead: 378 ALMs, zero M10K, measured, and padding the array to a
  // power of two on its own changed nothing (the bitstream came out
  // byte-identical, which is what gave it away).
  //
  // Reading every cycle regardless is what makes it a ROM, and it is safe
  // because every 12-bit address is in range now that there are 64 slots.
  logic [7:0] key_q;
  always_ff @(posedge clk) begin
    absent <= (slot == NONE);
    key_q  <= keys[addr];
  end

  assign key_data = absent ? 8'h00 : key_q;

endmodule
