#!/usr/bin/env python3
"""Generate the EEPROM default contents from MAME's source.

Two of the six games ship EEPROM defaults: Shogun Warriors and B.Rap Boys, 64
words each. Every other game starts from an erased 0xffff device, which is what
the EEPROM already does, so they get no entry here.

The defaults matter on a FIRST boot, where the HPS has no saved file to load.
B.Rap Boys' array is not just text -- it carries coinage, difficulty and a
service counter -- so an erased device is not the same as a defaulted one.

  tools/gen_eeprom_defaults.py        # writes rtl/io/eeprom_defaults.hex

BLOCK COMMENTS ARE STRIPPED FIRST, and that is not tidiness. kaneko16.cpp
carries TWO arrays named shogwarr_default_eeprom: an earlier one commented out
with the note "the above eeprom looks corrupt, some of the text is wrong", and
the live one below it. A parser that took the first match would take the
corrupt one, and the difference is readable text either way -- nothing would
look obviously wrong.

WHERE THE DATA COMES FROM

kaneko16.cpp, MAME, BSD-3-Clause (Luca Elia, David Haywood). GPL-compatible, so
it can live here with its attribution. It is not ROM-derived -- these are
defaults MAME's driver supplies, not anything read out of a dumped part -- so
hard rule 2 does not apply and there is nothing for an MRA to carry.
"""
import re
import sys
from pathlib import Path

SRC = Path("third_party/mame/src/mame/kaneko/kaneko16.cpp")
OUT = Path("rtl/io/eeprom_defaults.hex")

# Slot order must match the RTL's. Keyed by this core's game id.
GAMES = [("shogwarr", 4), ("brapboys", 5)]


def strip_block_comments(text):
    return re.sub(r"/\*.*?\*/", "", text, flags=re.S)


def parse(text, name):
    m = re.search(r"static const u16 " + name + r"\[64\]\s*=\s*\{(.*?)\}", text, re.S)
    if not m:
        sys.exit(f"{name} not found in {SRC} -- MAME's shape changed and this "
                 f"parser has not followed it")
    vals = [int(v, 16) for v in re.findall(r"0x([0-9a-fA-F]+)", m.group(1))]
    if len(vals) != 64:
        sys.exit(f"{name} parsed {len(vals)} words, expected 64")
    return vals


def main():
    if not SRC.exists():
        sys.exit(f"{SRC} not found; this reads MAME rather than keeping a copy")
    text = strip_block_comments(SRC.read_text(errors="replace"))

    # The corrupt array is inside a block comment, so stripping must have left
    # exactly one definition of each name. If two survive, the strip failed.
    for name, _ in [(f"{g}_default_eeprom", i) for g, i in GAMES]:
        if text.count(f"static const u16 {name}[64]") != 1:
            sys.exit(f"{name} appears "
                     f"{text.count(f'static const u16 {name}[64]')} times after "
                     f"stripping comments; expected exactly one")

    with OUT.open("w") as f:
        f.write("// Generated by tools/gen_eeprom_defaults.py -- do not edit.\n")
        f.write("// EEPROM defaults from MAME's kaneko16.cpp, BSD-3-Clause\n")
        f.write("// (Luca Elia, David Haywood). See that tool for why it is here.\n")
        for game, gid in GAMES:
            vals = parse(text, f"{game}_default_eeprom")
            f.write(f"// {game}, game id {gid}\n")
            for v in vals:
                f.write(f"{v:04x}\n")
            print(f"{game}: 64 words")

    print(f"{OUT}: {len(GAMES) * 64} words")


if __name__ == "__main__":
    main()
