#!/usr/bin/env python3
"""Generate the CALC3 key ROM from MAME's source.

The CALC3's keyed decryption path selects one of 256 64-byte keys by a byte in
the block header. MAME carries all 256 rows, but 220 of them are filled with
-1, its marker for "no such key" -- only 36 are real. Storing all 256 would be
16 KB and about 13 M10K; storing the 36 with a 256-entry index is 2.3 KB and
about 2, which matters on a device where block memory has been the binding
constraint for this branch.

The index maps a key byte to a slot, and a key byte with no key maps to
KEY_NONE. That is deliberately NOT a valid slot: a missing key must stop the
sequencer, not quietly decrypt with somebody else's key. MAME calls
fatalerror() there for the same reason.

  tools/gen_calc3_keys.py            # writes rtl/mcu/calc3_key*.hex

WHERE THE DATA COMES FROM, AND WHY IT IS COMMITTED

kaneko_calc3.cpp, MAME, BSD-3-Clause (Luca Elia, David Haywood). BSD-3 is
GPL-compatible, so it can live in a GPL-3.0-or-later repository with its
attribution kept.

It is NOT ROM-derived, and hard rule 2 therefore does not apply: the CALC3's
internal ROM has never been dumped, and this table is reverse-engineered
constants in MAME's source rather than anything extracted from a ROM image the
user supplies. There is nothing to load over MRA -- it is not in any romset.
Generating it at build time instead would make every build depend on a MAME
checkout, which a public repository should not require.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import importlib.util

spec = importlib.util.spec_from_file_location(
    "calc3_ref", Path(__file__).parent / "calc3_ref.py")
ref = importlib.util.module_from_spec(spec)
spec.loader.exec_module(ref)

KEY_NONE = 0x3f          # out of range for 36 slots, on purpose

OUT = Path("rtl/mcu")
HDR = ("// Generated by tools/gen_calc3_keys.py -- do not edit.\n"
       "// CALC3 key data from MAME's kaneko_calc3.cpp, BSD-3-Clause\n"
       "// (Luca Elia, David Haywood). See that tool for why it is committed.\n")


def main():
    key = ref.load_keydata()
    valid = [i for i, r in enumerate(key) if r[0] != -1]
    for i in valid:
        if any(v == -1 for v in key[i]):
            sys.exit(f"key row {i:02x} is partly -1; the compaction assumes a "
                     f"row is wholly valid or wholly absent")
    if len(valid) > KEY_NONE:
        sys.exit(f"{len(valid)} valid keys but the index reserves "
                 f"{KEY_NONE} as the absent marker")

    slot = {k: n for n, k in enumerate(valid)}

    keys = OUT / "calc3_keys.hex"
    with keys.open("w") as f:
        f.write(HDR)
        f.write(f"// {len(valid)} keys of 64 bytes, in ascending key order.\n")
        for k in valid:
            f.write(f"// key {k:02x}\n")
            for b in key[k]:
                f.write(f"{b & 0xff:02x}\n")

    idx = OUT / "calc3_keyidx.hex"
    with idx.open("w") as f:
        f.write(HDR)
        f.write(f"// key byte -> slot; {KEY_NONE:02x} means no such key.\n")
        for i in range(256):
            f.write(f"{slot.get(i, KEY_NONE):02x}\n")

    print(f"{keys}: {len(valid)} keys, {len(valid) * 64} bytes")
    print(f"{idx}: 256 entries, {256 - len(valid)} absent")


if __name__ == "__main__":
    main()
